Aplicacion Web 3/Controllers/ActividadesController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Aplicacion_Web_3.Models;

namespace Aplicacion_Web_3.Controllers
{
    public class ActividadesController : Controller
    {
        private ActividadesEntities db = new ActividadesEntities();

        // GET: Actividades
        public ActionResult InicioActividad()
        {
            if (Session["IdUsuario"] == null)
            {
                TempData["mensajeAlerta"] = "<script>alert('Debes estar logeado primero');</script>";
                return RedirectToAction("Inicio", "Ingresar");
            }
            else
            {
                ViewBag.listaActividades = (from a in db.tblActividades.AsEnumerable().Where(a => a.ActIdUsuario == Convert.ToInt32(Session["IdUsuario"]))
                                            select a).ToList();
                return View();
            }           
        }

        public ActionResult EditarActividad(int idActividad)
        {
               var actividad = db.tblActividades.Find(idActividad);
                if (actividad == null)
                {
                    return HttpNotFound();
                }

            return View(actividad);
        }

        [HttpPost]
        public ActionResult EditarActividad(tblActividades actividades)
        {
            if (ModelState.IsValid)
            {
                //actividades.ActIdUsuario = Convert.ToInt32(Session["IdUsuario"]);
                db.Entry(actividades).State = EntityState.Modified;
                db.SaveChanges();
            }

            return View(actividades);
        }

    }
}

Aplicacion Web 3/Controllers/HorasController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Aplicacion_Web_3.Models;

namespace Aplicacion_Web_3.Controllers
{
    public class HorasController : Controller
    {
        private ActividadesEntities db = new ActividadesEntities();

        // GET: Horas
        public ActionResult InicioHoras(int HorAct_IdActividad)
        {
            if (Session["IdUsuario"] == null)
            {
                TempData["mensajeAlerta"] = "<script>alert('Debes estar logeado primero');</script>";
                return RedirectToAction("Inicio", "Ingresar");
            }
            else
            {
                ViewBag.idHorActividad = HorAct_IdActividad;
                ViewBag.listaHoras = (from a in db.tblHorasActividades.AsEnumerable().Where(a => a.HorAct_IdActividad == HorAct_IdActividad)
                                      select new tblHorasActividades
                                      {
                                          HorAct_CantidadHoras = a.HorAct_CantidadHoras,
                                          HorAct_IdActividad = a.HorAct_IdActividad,
                                          HorAct_Fecha = a.HorAct_Fecha,
                                          HorAct_IdHoras = a.HorAct_IdHoras
                                      }).ToList();

                return View();
            }
        }
        
        public ActionResult EditarHoras(int HorAct_IdHoras)
        {
            var horas = db.tblHorasActividades.Find(HorAct_IdHoras);
            if (horas == null)
            {
                return HttpNotFound();
            }

            return View(horas);
        }

        [HttpPost]
        public ActionResult EditarHoras(tblHorasActividades horasActividades)
        {
            db.Entry(horasActividades).State = EntityState.Modified;
            db.SaveChanges();

            //var usuarioActual = db.usuario.FirstOrDefault(m => m.idUsuario == usuario.idUsuario);
            //usuarioActual.nombre = usuario.nombre;

            return View(horasActividades);
        }

    }
}

Aplicacion Web 3/Controllers/RegistroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Aplicacion_Web_3.Models;

namespace Aplicacion_Web_3.Controllers
{
    public class RegistroController : Controller
    {
        private ActividadesEntities db = new ActividadesEntities();

        // GET: Registro
        public ActionResult Index()
        {
            //var listaUsuarios = db.TblUsuarios.ToList();

            var listaUsuarios = (from A in db.TblUsuarios.AsEnumerable()
                             select new TblUsuarios
                             {
                                 IdUsuario = A.IdUsuario,
                                 NombreUsuario = A.NombreUsuario,
                                 Contrasenia = A.Contrasenia
                             }).ToList();

            return View(listaUsuarios);
        }

        // POST: Registro/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Registro/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Registro/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Registro/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Registro/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Aplicacion Web 3/Views/Actividades/EditarActividad.cshtml
@model Aplicacion_Web_3.Models.tblActividades

@{
    ViewBag.Title = "EditarActividad";
}

<h2>EditarActividad</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>tblActividades</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.idActividad)

        <div class="form-group">
            @Html.LabelFor(model => model.DescripcionActividad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DescripcionActividad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DescripcionActividad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                @Html.HiddenFor(model => model.ActIdUsuario)
                @Html.ValidationMessageFor(model => model.ActIdUsuario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Modificar" class="btn btn-create" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver", "InicioActividad")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Aplicacion Web 3/Views/Actividades/InicioActividad.cshtml
@model Aplicacion_Web_3.Models.tblActividades

@{
    ViewBag.Title = "Inicio";
}

<div class="Row">
    <div class="col-lg-1 aaa">
        @*<input type="button" value="Actividades" class="btn btn-primary elboton">*@
        @Html.ActionLink("Actividades", "InicioActividad", "Actividades", null, new { @class = "btn btn-primary elboton" })
        @Html.ActionLink("Usuarios", "Index", "Registro", null, new { @class = "btn btn-primary elboton" })
    </div>

    <div class="col-lg-11 formularioo">
        @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.DescripcionActividad, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.DescripcionActividad, new { htmlAttributes = new { @class = "form-control", @id = "DescripcionActividad" } })
                @Html.ValidationMessageFor(model => model.DescripcionActividad, "", new { @class = "text-danger" })
            </div>

            <input type="hidden" value=@Session["IdUsuario"] id="ActIdUsuario" />

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="button" value="Crear actividad" class="btn btn-default" id="btnCrearActividad" />
                </div>
            </div>
        </div>
}

        <table class="table table-bordered">
            <thead>
                <tr>
                    <td>Descripcion Actividad</td>
                    <td>Acciones</td>
                    <td>Editar</td>
                </tr>
            </thead>
            <tbody id="cuerpoTabla">
                @foreach (var item in ViewBag.listaActividades)
            {
                <tr>
                    <td>@item.DescripcionActividad</td>
                    <td>@Html.ActionLink("Agregar Horas", "InicioHoras", "Horas", new { HorAct_IdActividad = item.idActividad }, null)</td>
                    <td>@Html.ActionLink("Editar descripción", "EditarActividad", "Actividades", new { idActividad = item.idActividad }, null)</td>
                </tr>
        }
            </tbody>
        </table>
    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}